[ARV-62] 공연 기록 CRUD 구현
prgrms-web-devcourse-final-project/WEB1_1_Allreva_BE pull request #60
Opened 2024-11-29 03:21 UTC by kwanse

### 연결된 issue 🌟
ex) 연결된 issue를 자동으로 닫기 위해 # 다음 이슈 넘버를 입력해주세요. ex) #2 
<br>
- closed #49 

### 구현 내용 📢
공연 기록 CRUD 구현
 

### 테스트 결과 🧩
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
공연 기록 생성 응답
![image](https://github.com/user-attachments/assets/1070bd8f-2bc2-4559-ba24-0cfcb321995f)

공연 기록 수정 응답
![image](https://github.com/user-attachments/assets/3961d946-aede-4a55-9908-f6b8aba3cd70)

공연 기록 상세 조회 응답
![image](https://github.com/user-attachments/assets/9390523d-d9bf-4e9a-b22a-798d652ec311)

공연 기록 목록 조회 응답
![image](https://github.com/user-attachments/assets/464541f2-b311-4cd5-8ede-49c19f114b6c)

### 리뷰 포인트 📌
공연 기록 crud

2024-11-29 06:56 UTC, tnals2384 reviewed
고생하셨습니닷!!!

2024-11-29 06:56 UTC, tnals2384 commented on src/test/java/com/backend/allreva/concert/ConcertQueryTest.java
ㅠㅠ 비운의 테스트

2024-11-29 06:56 UTC, tnals2384 commented on src/main/java/com/backend/allreva/diary/command/application/DiaryCommandService.java
> +                .orElseThrow();
아무것도 안던지나요?!

2024-11-29 06:56 UTC, tnals2384 commented on src/main/java/com/backend/allreva/diary/exception/DiaryErrorCode.java
> +    DIARY_NOT_FOUND(HttpStatus.NOT_FOUND.value(), "DIARY_NOT_FOUND", "삭제할 권한이 없습니다");
메세지 바꿔야할것같아용!!

2024-11-29 10:05 UTC, sangcci requested changes
수고하셨습니당..! 👍

2024-11-29 10:05 UTC, sangcci commented on src/main/java/com/backend/allreva/diary/query/dto/DiaryDetailResponse.java
> +public final class DiaryDetailResponse {
record 어떠십니까..!

2024-11-29 17:24 UTC, kwanse commented on src/main/java/com/backend/allreva/diary/exception/DiaryErrorCode.java
> +    DiaryErrorCode(Integer status, String errorCode, String message) {
예리하시군요..! 수정완료!!!

2024-11-29 17:27 UTC, kwanse commented on src/main/java/com/backend/allreva/diary/query/dto/DiaryDetailResponse.java
> +public final class DiaryDetailResponse {
바로 수정했습니당! ~~~

2024-11-29 17:29 UTC, kwanse commented on src/main/java/com/backend/allreva/diary/command/application/DiaryCommandService.java
> +                .orElseThrow(DiaryNotFoundException::new);
상혁님처럼 도메인 안에 작성하는게 확실히 더 좋아보이네요!! 바로 수정했습니다잉~~ 요렇게 하면 될까용???

2024-11-29 17:30 UTC, kwanse commented on src/main/java/com/backend/allreva/diary/command/application/DiaryCommandService.java
> +            throw new DiaryNotWriterException();
대 상 혁

2024-11-30 07:17 UTC, tnals2384 approved these changes

2024-11-30 07:54 UTC, merged